import axios from 'axios'

export const FETCH_MOVIE_START = "FETCH_MOVIE_START"
export const FETCH_MOVIE_SUCCESS = "FETCH_MOVIE_SUCCESS"
export const FETCH_MOVIE_FAILURE = "FETCH_MOVIE_FAILURE"
export const POST_MOVIE_START = "POST_MOVIE_START"
export const POST_MOVIE_SUCCESS = "POST_MOVIE_SUCCESS"
export const POST_MOVIE_FAILURE = "POST_MOVIE_FAILURE"
export const PUT_MOVIE_START = "PUT_MOVIE_START"
export const PUT_MOVIE_SUCCESS = "PUT_MOVIE_SUCCESS"
export const PUT_MOVIE_FAILURE = "PUT_MOVIE_FAILURE"
export const DELETE_MOVIE_START = "DELETE_MOVIE_START"
export const DELETE_MOVIE_SUCCESS = "DELETE_MOVIE_SUCCESS"
export const DELETE_MOVIE_FAILURE = "DELETE_MOVIE_FAILURE"

